### PR TITLE
Lift ScmUnitRegistry and avoid unit_registry name collision

### PR DESCRIPTION
**Pull request by mikapfl**
# Pull request

Please confirm that this pull request has done the following:

- [ ] Tests added
- [x] Documentation added (where applicable)
- [ ] Example added (either to an existing notebook or as a new notebook, where applicable)
- [x] Description in ``CHANGELOG.rst`` added

## Adding to CHANGELOG.rst

Please add a single line in the changelog notes similar to one of the following:

```
- (`#XX <https://github.com/openscm/openscm-units/pull/XX>`_) Added feature which does something
- (`#XX <https://github.com/openscm/openscm-units/pull/XX>`_) Fixed bug identified in (`#YY <https://github.com/openscm/openscm-units/issues/YY>`_)
```

### CODE REVIEW

**Comment by znicholls** [comment]
@mikapfl if you rebase on master the CI should run (sorry I'd set it up incorrectly, see #15)

**Comment by mikapfl** [comment]
Quite a cool CI setup! It is a pleasure developing in such a well-set-up repository. (-:

**Comment by znicholls** [comment]
Beauty thanks

**Comment by znicholls** [comment]
0.2.0 up now https://pypi.org/project/openscm-units/0.2.0/

**Pull request merged**
