### PR TITLE
Generate static documentation from notebooks

### PR DESCRIPTION
**Pull request by mikapfl**
# Pull request

Please confirm that this pull request has done the following:

- [ ] Tests added
- [x] Documentation added (where applicable)
- [ ] Example added (either to an existing notebook or as a new notebook, where applicable)
- [x] Description in ``CHANGELOG.rst`` added

# Generate static documentation from notebooks

Follow-up to https://github.com/openscm/openscm-units/pull/21

I think it would be great if there was a usage introduction also at reathedocs.io. Because nobody wants to write the same documentation in a different format twice, I propose to generate the static usage documentation from the example notebooks that already exist.

### CODE REVIEW

**Comment by mikapfl** [comment]
Hm, notebook tests are either failing in python 3.7 or in 3.8 and 3.9. I chose the future-proof version which fails on python 3.7. Hope that's fine.

**Comment by mikapfl** [comment]
ping?

**Comment by znicholls** [comment]
oops sorry https://github.com/mikapfl/openscm-units/pull/1

**Comment by znicholls** [comment]
Merge when you've finished fighting black @mikapfl :)

**Pull request merged**
