### PR TITLE
Autorelease

### PR DESCRIPTION
**Pull request by mikapfl**
# Pull request

Please confirm that this pull request has done the following:

- [ ] Tests added
- [ ] Documentation added (where applicable)
- [ ] Example added (either to an existing notebook or as a new notebook, where applicable)
- [x] Description in ``CHANGELOG.rst`` added

## Adding to CHANGELOG.rst

Please add a single line in the changelog notes similar to one of the following:

```
- (`#XX <https://github.com/openscm/openscm-units/pull/XX>`_) Added feature which does something
- (`#XX <https://github.com/openscm/openscm-units/pull/XX>`_) Fixed bug identified in (`#YY <https://github.com/openscm/openscm-units/issues/YY>`_)
```

### CODE REVIEW

**Review by znicholls — APPROVED** [review]
Wicked, was probably some mucking around but can definitely be re-used!

**Comment by mikapfl** [comment]
If you want it merged, you have to do it yourself, I can't merge even though you have approved it. :slightly_smiling_face:

**Comment by znicholls** [comment]
I just gave you write access, can you merge now?

**Comment by znicholls** [comment]
Nice when it all works :) https://github.com/openscm/openscm-units/runs/3236053015?check_suite_focus=true

**Pull request merged**
