### PR TITLE
Updated outdated docs about NOx conversions.

### PR DESCRIPTION
**Pull request by mikapfl**
# Pull request

Please confirm that this pull request has done the following:

- [ ] Tests added
- [x] Documentation added (where applicable)
- [ ] Example added (either to an existing notebook or as a new notebook, where applicable)
- [x] Description in ``CHANGELOG.rst`` added

NOx is not a simple alias for NO2 any more. Update docs accordingly.

Prompted by https://github.com/pik-primap/primap2/discussions/96

### CODE REVIEW

**Comment by mikapfl** [comment]
The linting failure is fixed in https://github.com/openscm/openscm-units/pull/33/commits/0903fa52bf2692e3fd713a44fb1c1bbcac87affb . I think including it here as well would cause merge conflicts later on?

**Comment by mikapfl** [comment]
Ah, no, sorry, other problem. Apparently, a newer black version. May I interest you in https://pre-commit.ci/ for auto-fixing black commits?

**Comment by mikapfl** [comment]
The liniting failure which is *now* left is actually https://github.com/openscm/openscm-units/commit/0903fa52bf2692e3fd713a44fb1c1bbcac87affb .

**Comment by znicholls** [comment]
> May I interest you in https://pre-commit.ci/ for auto-fixing black commits?

Ye sure

> I think including it here as well would cause merge conflicts later on?

Ye up to you if you want to just wait for #33 or rebase #33 later

**Review by znicholls — APPROVED** [review]
awesome thanks!

**Pull request merged**
